#!/system/bin/sh
# 98kernelconfig v1 by Mr.MEX

######################
## BEGIN USER SETUP ##
######################
# CPU online
cpuonline=1

# CPU governor
cpugov=ondemandplus

# CPU min. freq.
min_freq=223000

# CPU max. freq.
max_freq=2265000

# Fast charging
fastcharge=1

# Scheduler
scheduler=vr
# The size of the read ahead buffer
readahead=3072

# Vibrator
vibrator=100

# WiFi wakelocks
bcmwakelocks=0
####################
## END USER SETUP ##
####################
chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
chmod 666 /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
chmod 666 /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
chmod 666 /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor

chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
chmod 666 /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
chmod 666 /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq
chmod 666 /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq

chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
chmod 666 /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
chmod 666 /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
chmod 666 /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq

chmod 666 /sys/devices/system/cpu/cpu1/online
chmod 666 /sys/devices/system/cpu/cpu2/online
chmod 666 /sys/devices/system/cpu/cpu3/online

chmod 666 /sys/kernel/fast_charge/force_fast_charge

chmod 666 /sys/devices/virtual/bdi/179:0/read_ahead_kb

chmod 666 /sys/class/timed_output/vibrator/amp

echo -n $cpuonline > /sys/devices/system/cpu/cpu1/online
echo -n $cpuonline > /sys/devices/system/cpu/cpu2/online
echo -n $cpuonline > /sys/devices/system/cpu/cpu3/online

echo -n $cpugov > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo -n $cpugov > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
echo -n $cpugov > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
echo -n $cpugov > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor

echo -n $min_freq > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo -n $min_freq > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
echo -n $min_freq > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq
echo -n $min_freq > /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq

echo -n $max_freq > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo -n $max_freq > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
echo -n $max_freq > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
echo -n $max_freq > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq

stop thermal-engine;

echo -n 0 > /sys/kernel/msm_mpdecision/conf/boost_enabled

stop mpdecision;

echo -n 0 > /sys/module/msm_thermal/core_control/enabled

echo -n $fastcharge > /sys/kernel/fast_charge/force_fast_charge

echo -n $scheduler > /sys/block/mmcblk0/queue/scheduler
echo -n $readahead > /sys/devices/virtual/bdi/179:0/read_ahead_kb

echo -n $vibrator > /sys/class/timed_output/vibrator/amp

echo -n $bcmwakelocks > /sys/module/wakeup/parameters/enable_wlan_rx_wake_ws
echo -n $bcmwakelocks > /sys/module/wakeup/parameters/enable_wlan_ctrl_wake_ws
echo -n $bcmwakelocks > /sys/module/wakeup/parameters/enable_wlan_wake_ws
echo -n $bcmwakelocks > /sys/module/wakeup/parameters/enable_si_ws